### ISSUE TITLE
Uncaught ReferenceError: remaining is not defined

### ISSUE THREAD

**Issue by CreativeTransmissions** [amandaghassaei/canvas-capture#10]
Hi there, this error occurs on load.

Installed using npm, using with a svelte project.

Fix should be just a case of defining the error before use.

Uncaught ReferenceError: remaining is not defined
    at LZWEncoder.encode (canvas-capture.js:3402:14556)
    at GIFEncoder.writePixels (canvas-capture.js:3402:12864)
    at GIFEncoder.addFrame (canvas-capture.js:3402:7599)
    at renderFrame (canvas-capture.js:3402:28769)
    at self.onmessage (canvas-capture.js:3402:29314)

**Comment by amandaghassaei** [comment]
oof, this error is coming from a pre-compiled dependency.  I've added a fix to the dev branch, can you test this by running:

```
npm install https://github.com/amandaghassaei/canvas-capture#dev
```

If that works, I'll merge it into main.

thanks!

**Comment by amandaghassaei** [comment]
ok I took a look at https://github.com/jnordberg/gif.js/blob/92d27a02841339e202c75150dcf6fe5f4fa42ec5/src/LZWEncoder.js

and realized that `remaining` and `curPixel` should be defined in the root of LZWEncoder, rather than inside a function.  I also found another variable `n_bits` that needed to be defined.  I've just commited the latest to the dev branch, let me know if that's working!

**Comment by symetryn** [comment]
@amandaghassaei Thank you for your work.
 After looking further I found that this issue didn't occur in incognito mode. I tried disabling extensions one by one and it seems some how this issue only occurs when the official [react dev tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) extension is enabled. It probably declares the variables in same scope as gif.js. So, this seems to be a non issue altogether.

**Comment by amandaghassaei** [comment]
@symetryn sounds good, thanks for looking into that.

@CreativeTransmissions does the current dev branch fix the svelte issue?  or do you have a project that I can take a look at to resolve this?  thanks!

**Comment by Paolino95** [comment]
Sorry, @amandaghassaei , do you have merge this last 4 commits into main branch?

![image](https://github.com/amandaghassaei/canvas-capture/assets/36879730/b3482ebc-7f45-4e15-9e3a-8da0232fce36)

Because in the main branch I have the same issue;

**Comment by amandaghassaei** [comment]
@Paolino95  I don't think I ever did because I was waiting to hear back if the changes I made had any effect.  Can you import the dev branch and test it?

```npm install git+https://github.com/amandaghassaei/canvas-capture.git#dev```

thanks

**Comment by junekuhn** [comment]
I had the same problem and the dev branch fixed it for me

**Comment by vesper8** [comment]
@amandaghassaei I installed your dev branch and it has indeed made the error go away. But now I'm on dev 2.0.5 instead of 2.1.1 so missing a few updates.

Any chance you could find the time to release 2.1.2 or 2.2 with the fix and the latest commits please?

Thanks
